# .github/workflows/release.yaml

on: 
  release:
    types: [created]

jobs:
  release-matrix:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: go test -v -p=1 -timeout=0 ./...
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd/gemini"
        binary_name: "gemini"
        extra_files: LICENSE "./cmd/gemini/README.md"
